### ISSUE TITLE
Help about usage ?

### ISSUE THREAD

**Issue by babarnazmi** [jtripper/plugin-based-irc-bot#2]
I am unable to use this code and your previous irc-bot was also not working for me, can you please guide how to use it? Commands help, any example etc.?

/msg love_pizza twitter.tweet my first tweet

PRIVMSG love_pizza :twitter.tweet my first tweet
('./main.py', 57, '<module>', 'ret = driver.run_command(bot, tmp, auth_level, sock)')
('/root/irc-tweet-bot/pluginDriver.py', 128, 'run_command', 'getattr(self.plugins[command[0]], command[1])(bot, sock, buffer)')
<type 'exceptions.TypeError'>
tweet() takes exactly 3 arguments (4 given)

PRIVMSG love_pizza :twitter.help(retweet)
('./main.py', 57, '<module>', 'ret = driver.run_command(bot, tmp, auth_level, sock)')
('/root/irc-tweet-bot/pluginDriver.py', 124, 'run_command', 'self.plugins[command[0]].help(bot, sock, buffer)')
<type 'exceptions.TypeError'>
help() takes exactly 3 arguments (4 given)

I also tried in main channel, private chat, but same error above (with double quote, round brackets but none of them working)
twitter.tweet my first tweet

Please tell me what I am doing wrong?

Thanks,

**Comment by martijngonlag** [comment]
Try running the `fix_plugins.sh` found here: https://github.com/jtripper/plugin-based-irc-bot/blob/master/fix_plugins.sh

After this run `twitter.tweet my first tweet!` in the main channel where the bot is located and it should work.

**Comment by babarnazmi** [comment]
After running fix_plugins.sh the behavior is same

twitter.tweet my first tweet gaves me same error:
('./main.py', 57, '<module>', 'ret = driver.run_command(bot, tmp, auth_level, sock)')
('/root/irc-tweet-bot/pluginDriver.py', 149, 'run_command', 'getattr(self.plugins[command[0]], command[1])(bot, sock, buffer)')
<type 'exceptions.TypeError'>
tweet() takes exactly 3 arguments (4 given)

also 'twitter' is a reserved word ? I have to change the plugin class to something else or else I got this error:

./main.py 
Traceback (most recent call last):
  File "./main.py", line 40, in <module>
    bot, driver = init()
  File "./main.py", line 36, in init
    driver.load_plugins("plugins")
  File "/root/irc-tweet-bot/pluginDriver.py", line 70, in load_plugins
    self.plugins[module] = **import**(module).**dict**[module]()
KeyError: 'twitter'

**Comment by martijngonlag** [comment]
Have you set everything up correctly in the `config.py`?

**Comment by babarnazmi** [comment]
Yes 100%, it is giving same error with all plugins, bot is connecting to IRC server and also replying auth.level commands, but whenever I try any plugin it gave me same error 
tweet() takes exactly 3 arguments (4 given) //twitter.tweet
help()  takes exactly 3 arguments (4 given) //twitter.help
nick()  takes exactly 3 arguments (4 given) //control.nick

:Bravo!ircap@silicon-dialup--B0529F34 PRIVMSG #BChat :control.nick new
('main.py', 57, '<module>', 'ret = driver.run_command(bot, tmp, auth_level, sock)')
('V:\irc-tweet-bot\pluginDriver.py', 149, 'run_command', 'getattr(self.plugins[command[0]], command[1])(bot, sock, buffer)')
<type 'exceptions.TypeError'>
nick() takes exactly 3 arguments (4 given)

Where 'Bravo' is the bot operator nick with auth.level 10, #BChat is the channel name
control.nick is the plugin command.

**Comment by babarnazmi** [comment]
Can you please confirm me your version of python?

I tried with 2.7 & 2.6 on both linux and windows but with same errors.
Just tried with Python 3.4.1, not working, tried to fix some syntax errors but it looks current code doesn't support Python 3.4.1 (as of yet).

**Comment by babarnazmi** [comment]
I think  fix_plugins.sh command is doing nothing, can someone help here? or share fixed version of plugins? or any clue?

**Comment by jtripper** [comment]
I can't reproduce this issue. Please be sure you are running the most recent version.

**Comment by babarnazmi** [comment]
I am running the latest code, tried on Linux (CentOS + Python 2.7) and Windows 7 (Python 2.7) machine. Same error in both. It looks fix_plugins.sh (sed command) is not doing/replacing any code. 

Bot is connecting, replying to auth.level commands, but none of the plugin is working. When ever I try any plugin command it gaves me error in pluginDriver.py 
command takes exactly 3 arguments (4 given)

**Comment by jtripper** [comment]
Sorry, I'm totally unable to reproduce this issue.

**Comment by ghost** [comment]
@babarnazmi Delete your copy of the bot and clone it again. `git clone https://github.com/jtripper/plugin-based-irc-bot.git`

When you've cloned it, do not edit any files except config.py and test if it works now.

**Comment by babarnazmi** [comment]
Yes, it is working now :)
Thanks a lot Sir @norwack
