### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by babarnazmi** [jtripper/plugin-based-irc-bot#6]
Is it possible to use one bot and loop list of Auth keys/tokens for multiple accounts ?

Like I want to tweet from 10 different accounts, I have to run 10 instances of bot (only the config.py is different), is it possible to use 10 Auth keys/tokens in an array/from flat file or db backend (etc), so bot can loop and tweet ?

Best Regards,

**Comment by ghost** [comment]
Yes, this is possible. However you have to modify the twitter plugin.

**Comment by babarnazmi** [comment]
Thanks a lot Sir, I will try my luck with the twitter plugin code !

**Comment by ghost** [comment]
If you can't figure it out, please let me know - i might have time to write plugin for this on sunday or so.

**Comment by babarnazmi** [comment]
I am trying, but my programming skills are below average, Sir it will be great if you do so :)

**Comment by ghost** [comment]
@babarnazmi Better late than never, i don't do much Python at the moment. However, something like this should do the job.

```
>>> twitter_keys = []
>>> new_keyset = {"app-key": "APP_KEY", "app-secret": "APP_SECRET", "user-token": "USER_TOKEN", "user-secret": "USER_SECRET"}
>>> twitter_keys.append(new_keyset)
>>> for keyset in twitter_keys:
...     print "APP KEY: %s\nAPP SECRET: %s\nUSER TOKEN: %s\nUSER SECRET: %s\n" % (keyset["app-key"], keyset["app-secret"], keyset["user-token"], keyset["user-secret"]) 
... 
APP KEY: APP_KEY
APP SECRET: APP_SECRET
USER TOKEN: USER_TOKEN
USER SECRET: USER_SECRET

>>> 
```
